env:
  URLPERL: https://www.cpan.org/src/5.0/perl-5.40.0.tar.gz
  EMSCRIPTEN_VERSION: 3.1.73
  EXIFTOOL_VERSION: 13.11

jobs:
  perlemscripten:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v13
        with:
          version: ${{env.EMSCRIPTEN_VERSION}}

      - name: Install Perl static native
        shell: bash
        run: |
          mkdir native && curl -L $URLPERL | tar -xzf - --strip-components=1 --directory=native
          cd native
          sh +x ./Configure -sde -Dman1dir=none -Dman3dir=none -Dprefix="$PWD/prefix" -Dusedevel -Uversiononly -Dlibs="-lpthread -ldl -lm -lutil -lc -lz" -Dstatic_ext="mro Devel/Peek File/DosGlob File/Glob Sys/Syslog Sys/Hostname PerlIO/via PerlIO/mmap PerlIO/encoding B attributes Unicode/Normalize Unicode/Collate threads threads/shared IPC/SysV re Digest/MD5 Digest/SHA SDBM_File Math/BigInt/FastCalc Data/Dumper I18N/Langinfo Time/HiRes Time/Piece IO Socket Hash/Util/FieldHash Hash/Util Filter/Util/Call POSIX Encode/Unicode Encode Encode/JP Encode/KR Encode/EBCDIC Encode/CN Encode/Symbol Encode/Byte Encode/TW Compress/Raw/Zlib Compress/Raw/Bzip2 MIME/Base64 Cwd Storable List/Util Fcntl Opcode"
          make
          make install

      - name: Download and Embed ExifTool
        shell: bash
        run: |
          mkdir exiftool && curl -L https://exiftool.org/Image-ExifTool-${{env.EXIFTOOL_VERSION}}.tar.gz | tar -xzf - --strip-components=1 --directory=exiftool
          cd exiftool
          perl Makefile.PL
          make
          make install DESTDIR=$PWD/prefix
          cd ..

      - name: Install Perl static wasm
        shell: bash
        run: |
          mkdir wasm && curl -L $URLPERL | tar -xzf - --strip-components=1 --directory=wasm
          cp hintfile_wasm.sh wasm/hints/emscripten.sh
          cp -r exiftool/prefix/* wasm/

          cd wasm
          emconfigure sh ./Configure -sde -Dinc_version_list=none -Ddlsrc=none -Dloclibpth='' -Dglibpth='' -Dlns='/bin/ln' -Dman1dir=none -Dman3dir=none -Dosname="emscripten" -Darchname="wasm" -Dosvers="2.0.5" -Dmyhostname='localhost' -Dmydomain='.local' -Dperladmin=root -Dcc=emcc -Dld=emcc -Dar=$(which emar) -Dranlib=$(which emranlib) -Doptimize="-O2" -Dlibs='-lm' -Dhintfile=emscripten -Dsysroot=$(dirname $(which emcc))/system -Dhostperl=$PWD/../native/miniperl -Dhostgenerate=$PWD/../native/generate_uudmap -Dprefix=$PWD/prefix -Dstatic_ext="mro Devel/Peek File/DosGlob File/Glob Sys/Syslog Syslog.a lib/auto/Socket/Socket.a lib/auto/Hash/Util/FieldHash/FieldHash.a lib/auto/Hash/Util/Util.a lib/auto/Filter/Util/Call/Call.a lib/auto/POSIX/POSIX.a lib/auto/Encode/Unicode/Unicode.a lib/auto/Encode/Encode.a lib/auto/Encode/JP/JP.a lib/auto/Encode/KR/KR.a lib/auto/Encode/EBCDIC/EBCDIC.a lib/auto/Encode/CN/CN.a lib/auto/Encode/Symbol/Symbol.a lib/auto/Encode/Byte/Byte.a lib/auto/Encode/TW/TW.a lib/auto/Compress/Raw/Zlib/Zlib.a lib/auto/Compress/Raw/Bzip2/Bzip2.a lib/auto/MIME/Base64/Base64.a lib/auto/Cwd/Cwd.a lib/auto/Storable/Storable.a lib/auto/List/Util/Util.a lib/auto/Fcntl/Fcntl.a lib/auto/Opcode/Opcode.a"

          ln -s $PWD/pod/perldelta.pod .; ln $PWD/README.* ..
          emmake make utilities PERL="$PWD/../native/miniperl"
          emmake make       RUN_PERL="$PWD/../native/miniperl -Ilib -I."
          chmod +x ./perl
          emmake make install
          node ./prefix/bin/perl -e 'print("hello world\n");'

          find ./prefix -type f -executable -o -name '*.so' -name '*.a' -o -name '*.ld' -o -name '*.pod' -o -name '*.h' -delete
          emcc -o perlembed --embed-file $PWD/prefix@$PWD/prefix -lm -O2 -s SINGLE_FILE=1 -s NO_EXIT_RUNTIME=1 -s ALLOW_MEMORY_GROWTH=1 -Wno-almost-asm -s ERROR_ON_UNDEFINED_SYMBOLS=0 -s WASM=1 -fstack-protector-strong perlmain.o

          node ./perlembed -e 'print(join(":",@INC),"\n");'
          node ./perlembed -e 'use Cwd;print(Cwd::cwd(),"\n");'
          node ./perlembed -e 'system("exiftool -ver");'

      - name: Artifacts
        uses: actions/upload-artifact@v4
        with:
          path: |
            wasm/config.h
            wasm/perlembed
