name: perlwasi

on: workflow_dispatch

env:
  URLPERL: https://www.cpan.org/src/5.0/perl-5.40.0.tar.gz
  WASI_SDK_VERSION: "20.0"
  WASI_SDK_URL: https://github.com/WebAssembly/wasi-sdk/releases/download/wasi-sdk-20.0/wasi-sdk-20.0-linux.tar.gz

jobs:
  build-perl-wasi:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup WASI SDK
        run: |
          mkdir wasi-sdk
          curl -L ${{ env.WASI_SDK_URL }} | tar -xzf - --strip-components=1 -C wasi-sdk
          echo "WASI_SDK_PATH=$(pwd)/wasi-sdk" >> $GITHUB_ENV
          echo "PATH=${{ env.WASI_SDK_PATH }}/bin:$PATH" >> $GITHUB_ENV

      - name: Install Native Perl for Bootstrapping
        run: |
          mkdir native && curl -L ${{ env.URLPERL }} | tar -xzf - --strip-components=1 --directory=native
          cd native
          sh ./Configure -des -Dprefix=$PWD/prefix -Duseshrplib
          make
          make install

      - name: Configure Perl for WASI
        run: |
          mkdir wasm && curl -L ${{ env.URLPERL }} | tar -xzf - --strip-components=1 --directory=wasm
          cd wasm
          cat <<'EOF' > hints/wasi.sh
            # Custom hints file for WASI
            usemymalloc="n"
            uselargefiles="undef"
            usenm="undef"
            cc="clang --sysroot=$WASI_SDK_PATH/share/wasi-sysroot"
            ld="wasm-ld --sysroot=$WASI_SDK_PATH/share/wasi-sysroot"
            cppflags="-D_GNU_SOURCE -D_POSIX_C_SOURCE=200809L"
            ccflags="-O2"
            ldflags="-lm"
            libpth="$WASI_SDK_PATH/share/wasi-sysroot/lib/wasm32-wasi"
            optimize="-O2"
            dlsrc="none"
            d_gethostbyname_r="undef"
            d_gethostbyaddr_r="undef"
            d_setjmp="define"
            d_longdbl="undef"
            d_readdir="define"
          EOF

          sh ./Configure -des -Darchname=wasi -Dprefix=$PWD/prefix \
            -Dcc=clang -Dld=wasm-ld -Dhintfile=hints/wasi.sh \
            -Dusethreads -Duseshrplib -Uuse64bitint -Uuse64bitall \
            -Dsysroot=$WASI_SDK_PATH/share/wasi-sysroot -Uversiononly
          
      - name: Build and Install Perl for WASI
        run: |
          cd wasm
          make
          make install

      - name: Test WASI Binary
        run: |
          cd wasm/prefix/bin
          wasmtime --dir=. ./perl -e 'print "Hello from WASI Perl!\n";'

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: perl-wasi-binaries
          path: wasm/prefix
