name: perlemscripten

on: workflow_dispatch
env:
  URLPERL: https://www.cpan.org/src/5.0/perl-5.40.0.tar.gz
  EMSCRIPTEN_VERSION: 3.1.73
  EXIFTOOL_VERSION: 13.11

jobs:
  perlemscripten:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v13
        with:
          version: ${{ env.EMSCRIPTEN_VERSION }}

      - name: Install Perl Static Native
        shell: bash
        run: |
          mkdir native && curl -L $URLPERL | tar -xzf - --strip-components=1 --directory=native
          cd native
          sh +x ./Configure -sde -Dman1dir=none -Dman3dir=none -Dprefix="$PWD/prefix" -Dusedevel -Uversiononly \
            -Dlibs="-lpthread -ldl -lm -lutil -lc -lz" \
            -Dstatic_ext="mro Devel/Peek File/DosGlob File/Glob Sys/Syslog Sys/Hostname PerlIO/via PerlIO/mmap PerlIO/encoding B attributes Unicode/Normalize Unicode/Collate threads threads/shared IPC/SysV re Digest/MD5 Digest/SHA SDBM_File Math/BigInt/FastCalc Data/Dumper I18N/Langinfo Time/HiRes Time/Piece IO Socket Hash/Util/FieldHash Hash/Util Filter/Util/Call POSIX Encode/Unicode Encode Encode/JP Encode/KR Encode/EBCDIC Encode/CN Encode/Symbol Encode/Byte Encode/TW Compress/Raw/Zlib Compress/Raw/Bzip2 MIME/Base64 Cwd Storable List/Util Fcntl Opcode"
          make
          make install
          chmod +x ./prefix/bin/perl

      - name: Download and Embed ExifTool
        shell: bash
        run: |
          mkdir exiftool && curl -L https://exiftool.org/Image-ExifTool-${{ env.EXIFTOOL_VERSION }}.tar.gz | tar -xzf - --strip-components=1 --directory=exiftool
          cd exiftool
          ../native/prefix/bin/perl Makefile.PL
          make
          make install DESTDIR=$PWD/prefix
          cd ..

      - name: Create Hint File for Emscripten
        run: |
          cat <<'EOF' > hintfile_wasm.sh
          usemymalloc="n"
          uselargefiles="n"
          usenm='undef'
          usemallocwrap="define"
          d_procselfexe='undef'
          d_dlopen='undef'
          d_setrgid='undef'
          d_setruid='undef'
          d_setproctitle='undef'
          d_malloc_size='undef'
          d_malloc_good_size='undef'
          d_fdclose='undef'
          d_clearenv='undef'
          d_cuserid='undef'
          d_eaccess='undef'
          d_getspnam='undef'
          d_sigsetjmp='undef'
          ldflags="-lm -O2 -s NO_EXIT_RUNTIME=1 -s ALLOW_MEMORY_GROWTH=1 -Wno-almost-asm -s ERROR_ON_UNDEFINED_SYMBOLS=0 -s WASM=1 -s SINGLE_FILE=1"
          ccflags="-D_GNU_SOURCE -D_POSIX_C_SOURCE -DNO_MATHOMS -Wno-null-pointer-arithmetic"
          cppflags="-lm -s ERROR_ON_UNDEFINED_SYMBOLS=0 -D_GNU_SOURCE -D_POSIX_C_SOURCE -DSTANDARD_C -DPERL_USE_SAFE_PUTENV -DNO_MATHOMS -Wno-null-pointer-arithmetic -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include"
          EOF

      - name: Install Perl Static WASM
        shell: bash
        run: |
          mkdir wasm && curl -L $URLPERL | tar -xzf - --strip-components=1 --directory=wasm
          cp hintfile_wasm.sh wasm/hints/emscripten.sh
          cd wasm
          emconfigure sh ./Configure -sde -Dinc_version_list=none -Ddlsrc=none -Dloclibpth='' -Dglibpth='' -Dlns='/bin/ln' \
            -Dman1dir=none -Dman3dir=none -Dosname="emscripten" -Darchname="wasm" -Dosvers="2.0.5" -Dmyhostname='localhost' \
            -Dmydomain='.local' -Dperladmin=root -Dcc=emcc -Dld=emcc -Dar=$(which emar) -Dranlib=$(which emranlib) \
            -Doptimize="-O2" -Dlibs='-lm' -Dhintfile=emscripten -Dsysroot=$(dirname $(which emcc))/system \
            -Dhostperl=$PWD/../native/miniperl -Dhostgenerate=$PWD/../native/generate_uudmap -Dprefix=$PWD/prefix \
            -Dstatic_ext="mro Devel/Peek File/DosGlob File/Glob Sys/Syslog Sys/Hostname PerlIO/via PerlIO/mmap PerlIO/encoding B attributes Unicode/Normalize Unicode/Collate threads threads/shared IPC/SysV re Digest/MD5 Digest/SHA SDBM_File Math/BigInt/FastCalc Data/Dumper I18N/Langinfo Time/HiRes Time/Piece IO Socket Hash/Util/FieldHash Hash/Util Filter/Util/Call POSIX Encode/Unicode Encode Encode/JP Encode/KR Encode/EBCDIC Encode/CN Encode/Symbol Encode/Byte Encode/TW Compress/Raw/Zlib Compress/Raw/Bzip2 MIME/Base64 Cwd Storable List/Util Fcntl Opcode"
          emmake make utilities PERL="$PWD/../native/miniperl"
          emmake make RUN_PERL="$PWD/../native/miniperl -Ilib -I."
          chmod +x ./perl
          emmake make install
          node ./prefix/bin/perl -e 'print("hello world\n");'
          find ./prefix -type f -executable -o -name '*.so' -name '*.a' -o -name '*.ld' -o -name '*.pod' -o -name '*.h' -delete
          find ./prefix
          emcc -o perlembed --embed-file $PWD/prefix@$PWD/prefix -lm -O2 -s SINGLE_FILE=1 -s NO_EXIT_RUNTIME=1 -s ALLOW_MEMORY_GROWTH=1 \
            -Wno-almost-asm -s ERROR_ON_UNDEFINED_SYMBOLS=0 -s WASM=1 -fstack-protector-strong perlmain.o
          node ./perlembed -e 'print(join(":",@INC),"\n");'
          node ./perlembed -e 'use Cwd;print(Cwd::cwd(),"\n");'

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          path: |
            wasm/config.h
            wasm/perlembed
